apiVersion: v1
kind: Secrets
metadata:
  name: my-secret
type: Opaque
data:
  username: dXNlcm5hbWU=  # base64 encoded value of "username"
  password: cGFzc3dvcmQ=  # base64 encoded value of "password"